language: python
sudo: required
services:
- docker
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 2.7
install:
- python patch_swagger.py
- "./generate_api.sh"
- pip install -U tox-travis
- pip install twine
script:
- tox
jobs:
  include:
    - stage: deploy_docs
      script:
        - set -e
        - pip install doctr
        - pip install -r docs-requirements.txt
        - cd docs
        - make html
        - cd ..
        - python -m doctr deploy docs
        - python -m doctr deploy --sync --no-require-master  --built-docs docs/_build/html "docs-$TRAVIS_BRANCH";
      python: 3.5
after_success:
- "./upload_pypi.sh"
deploy:
  provider: releases
  api_key:
    secure: P9EDLAG1WQfnPSfSTNMWcrTCaueSY2QpvUxKEFgKd8r9KmlgnensARMCbBsSMHVophI0v4q9Uwlej3a6BiWSTHa47AyuK85x4ZvQ55dmQbZdX5syfDnUygfnq3xQRbanOyeAtvqpwyAXqgUTfK1Xyg5yrojVgtd13WOT6o9tWZAjCEJJ3Nr8gLxtFmE8HV8J3qrjYLDA5RjWgP7D3xrik+bR+ydb/tXZ3YxGcqrPTDDi1c9dBBtqa+xcbfkADsjB08nkRCWzATwyrm21c3ZrNt6BbvRsPR3zij6bztZBa0GQtoIUyHg7Jcm/Bdzz/JwQBra2LYmur4zHFfsyEIX0Y+rdjCvMBCmkQXCVTlE+mXQwy9hnFSI+iWZjNmPLeCW6GUkyAyqu5GAcCXn/XLUvoL/7CB2VfVZXY0GD+jF52ZMhRnThXtHzcGQVYZk6UmKRKwYgcRs+ELasZKKsvEdjc0j36CJlSvaAdwlHdKLIjKDge1jAcHjmuHRVfztwF3vXmhIU2x/87u+dADizLuBHmjXHCWfm1sHwQr+wDybz5qA3L+zfrBZ1cmzQLa6OzgUphyg/SM/7dSjIkBvSvPvzM+S+gOwMprMKeA2y1SsWlq/OpTBCsg1FwKptUn3/51LBppGGQKx0A8sirzRnTXYF4rhoOHoSLXYvmMpFW08yPko=
  file_glob: true
  file:
    - dist/*
    - rebrickable-api.tar.gz
  on:
    repo: rienafairefr/pyrebrickable
    tags: true
env:
  global:
    # Doctr deploy key for rienafairefr/pyrebrickable
    - secure: "UARzXIwEGzY4ngPgGriYvCmFGz3Pip3SkMVAzfaa9oSC09/eyGBF9GuN4QwuXX/KeC2Zieto1p/BoWx3+OZ2AL1oJQbQZRCLkmh2apxR5oYC4w+//DxWoO/oLZFODFPgDbvV/3u8jaLfo1EWIYBfzYrHdD2A7Lii0goJl3hE42CAZAE5EEb7oEewok+b5d4HX7UXBN9CWPV7xF3+xPGfkf9Y0NOCysI/655D9Uzj9tYH9sjlT1hGRhuOAcUpUzQ9DfQ/sEec9gakHHJLcCGpz9lsZJiyXWtgXroN0iT3QBbqhAkCbyHxs6eJ0I2oVdJ5ottTfRnsBKl24fJ8u5A7s3JuBM7becoHoQPvQsYHoO7lblcrV4Zw63BGJKVeCqZZ5I1SE+ywVVcGydsbYcAsDI8NCNIOkTXfx2E2jQF1L8H8moKpAKbk0v29yGvEB7zn7FUv/RxNPUf0F3ZjyyKVXDt99Lz8Y/C41armfoJeWEnA2W0TRP2t5zMl4oAAOdNPAQb+Zb7DWo8hEWYgv5DPPqd41+AyJZotBB1jqw4shTtHyjeTlmSgwwuDyJmqqyTtlTRA0IXe0aZAXMlKfvYQIem+86kVs0LbHQ7zgJvddVx7x5k41wwPrb0pPMMLXnKoqks1/UUoaG3iWNPrNDef5OQ60OS2SGvmylGZz63DkmU="