language: python
sudo: required
services:
- docker
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 2.7
install:
- python patch_swagger.py
- "./generate_api.sh"
- pip install -U tox-travis
- pip install twine
script:
- tox
after_success:
- ./upload_pypi.sh
